#!/usr/bin/env bash
# scripts/bench.sh - canonical bench entry point for dinov2.cpp.
#
# Produces a markdown table at --out (default ./benchmark_results.md) by
# running the dinov2-cli binary with --bench across a models sweep.
#
# Quantization: only f16 GGUFs are supported as input. Pre-quantized GGUFs
# can be produced with the HF pipeline (workflow: convert-and-publish-gguf.yml)
# or downloaded from dinov2-cpp-core/<variant>-gguf on Hugging Face.
#
# Usage:
#   scripts/bench.sh                                # default sweep (all 4 model sizes, f16)
#   scripts/bench.sh --models small,base --repeats 5
#   scripts/bench.sh --aggregate ./per-platform/*.txt --out benchmark_results.txt
#
# Flags:
#   --models <csv>     comma-separated variants: small,base,large,giant and
#                      small-registers,base-registers,large-registers,giant-registers
#                      (default: small,base,large,giant)
#   --repeats <N>      timed runs per cell (default: 5)
#   --threads <N>      -t argument forwarded to dinov2-cli (default: 12)
#   --warmup <N>       --bench-warmup forwarded to dinov2-cli (default: 1)
#   --image <PATH>     input image (default: assets/tench.jpg)
#   --bin <PATH>       path to dinov2-cli binary (default: build/bin/dinov2-cli)
#   --out <PATH>       output markdown table (default: ./benchmark_results.md)
#   --platform <NAME>  platform label for the table header (default: detected)
#   BENCH_BUILD_CONFIG  build configuration recorded in output (default: unknown)
#   --aggregate <globs> --out <PATH>  aggregate mode: concatenate per-platform
#                                     *-results.txt files with platform headers.
#                                     --models/--repeats/--threads are ignored
#                                     in this mode.
#
# Exit codes:
#   0  success
#   1  invocation error
#   2  a required model GGUF is missing (recoverable: download from
#      dinov2-cpp-core/<variant>-gguf first)

set -euo pipefail

# ----------------- defaults -----------------
MODELS_DEFAULT="small,base,large,giant"
REPEATS_DEFAULT=5
THREADS_DEFAULT=12
WARMUP_DEFAULT=1
IMAGE_DEFAULT="assets/tench.jpg"
BIN_DEFAULT="build/bin/dinov2-cli"
OUT_DEFAULT="./benchmark_results.md"
PLATFORM_DEFAULT="$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)"
GIT_SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"

# ----------------- argparse -----------------
usage() {
    sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

MODELS=""
REPEATS=""
THREADS=""
WARMUP=""
IMAGE=""
BIN_PATH=""
OUT_PATH=""
PLATFORM_LABEL=""
AGGREGATE_INPUTS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage 0 ;;
        --models)        MODELS="${2:?}"; shift 2 ;;
        --repeats)       REPEATS="${2:?}"; shift 2 ;;
        --threads)       THREADS="${2:?}"; shift 2 ;;
        --warmup)        WARMUP="${2:?}"; shift 2 ;;
        --image)         IMAGE="${2:?}"; shift 2 ;;
        --bin)           BIN_PATH="${2:?}"; shift 2 ;;
        --out)           OUT_PATH="${2:?}"; shift 2 ;;
        --platform)      PLATFORM_LABEL="${2:?}"; shift 2 ;;
        --aggregate)     shift; while [[ $# -gt 0 && "$1" != --* ]]; do AGGREGATE_INPUTS+=("$1"); shift; done ;;
        *)               echo "bench.sh: unknown argument: $1" >&2; usage 1 ;;
    esac
done

MODELS="${MODELS:-$MODELS_DEFAULT}"
REPEATS="${REPEATS:-$REPEATS_DEFAULT}"
THREADS="${THREADS:-$THREADS_DEFAULT}"
WARMUP="${WARMUP:-$WARMUP_DEFAULT}"
IMAGE="${IMAGE:-$IMAGE_DEFAULT}"
BIN_PATH="${BIN_PATH:-$BIN_DEFAULT}"
OUT_PATH="${OUT_PATH:-$OUT_DEFAULT}"
PLATFORM_LABEL="${PLATFORM_LABEL:-$PLATFORM_DEFAULT}"

# ----------------- aggregate mode -----------------
if [[ ${#AGGREGATE_INPUTS[@]} -gt 0 ]]; then
    : > "$OUT_PATH"
    for f in "${AGGREGATE_INPUTS[@]}"; do
        if [[ ! -f "$f" ]]; then
            echo "::error::aggregate input not found: $f" >&2
            exit 1
        fi
        # Platform label = filename stem before "-results.txt"
        file_stem="${f##*/}"
        file_stem="${file_stem%-results.txt}"
        {
            echo "# ===== platform: ${file_stem} ====="
            cat "$f"
            echo ""
        } >> "$OUT_PATH"
    done
    echo "bench.sh: aggregated ${#AGGREGATE_INPUTS[@]} files -> $OUT_PATH" >&2
    exit 0
fi

# ----------------- main bench mode -----------------
if [[ ! -x "$BIN_PATH" ]]; then
    echo "::error::dinov2-cli binary not found at $BIN_PATH. Build first (cmake --build build --target dinov2-cli)." >&2
    exit 1
fi

if [[ ! -f "$IMAGE" ]]; then
    echo "::error::input image not found at $IMAGE." >&2
    exit 1
fi

IFS=',' read -ra MODEL_ARR <<< "$MODELS"

# Header (markdown table file). Only published f16 GGUFs are supported; the
# table has one row per model with mean/stddev/min/max/peak RSS columns.
{
    echo "# Generated by scripts/bench.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand."
    echo "# Platform: ${PLATFORM_LABEL}"
    echo "# Runner: $(uname -srm), $(nproc 2>/dev/null || getconf _NPROCESSORS_ONLN) logical CPUs"
    echo "# Git SHA: ${GIT_SHA}"
    echo "# Build configuration: ${BENCH_BUILD_CONFIG:-unknown}"
    echo "# Precision: f16 GGUF; backend: CPU; batch: 1"
    echo "# Image path: ${IMAGE}"
    echo "# Methodology: ${REPEATS} timed runs after ${WARMUP} warmup; threads: ${THREADS}. See docs/benchmarks.md."
    echo "# Command: scripts/bench.sh --models ${MODELS} --repeats ${REPEATS} --threads ${THREADS} --warmup ${WARMUP} --image ${IMAGE} --bin ${BIN_PATH} --out ${OUT_PATH}"
    echo ""
    echo "| Model | GGUF path | GGUF SHA256 | mean (ms) | stddev (ms) | min (ms) | max (ms) | peak RSS (MB) |"
    echo "|:------|:----------|:------------|----------:|------------:|---------:|---------:|---------------:|"
} > "$OUT_PATH"

for v in "${MODEL_ARR[@]}"; do
    case "$v" in
        small|base|large|giant)
            full_model="dinov2-vit-${v}-patch14"
            ;;
        small-registers|base-registers|large-registers|giant-registers)
            full_model="dinov2-with-registers-${v%-registers}-patch14"
            ;;
        *)
            echo "::error::unsupported model variant: ${v}" >&2
            exit 1
            ;;
    esac
    base_gguf="models/${full_model}/model.gguf"

    if [[ ! -f "$base_gguf" ]]; then
        echo "::error::Missing ${base_gguf}. Download the matching published f16 GGUF first." >&2
        exit 2
    fi
    gguf_sha256="$(sha256sum "$base_gguf" | cut -d ' ' -f 1)"

    echo "bench.sh: running ${full_model} repeats=${REPEATS} threads=${THREADS}..." >&2

    bench_json="$(mktemp)"
    trap 'rm -f "$bench_json"' EXIT

    if ! "$BIN_PATH" \
            -m "$base_gguf" \
            -i "$IMAGE" \
            -t "$THREADS" \
            -c \
            --bench-runs "$REPEATS" \
            --bench-warmup "$WARMUP" \
            --bench-json \
            > "$bench_json" 2>/dev/null; then
        echo "::error::dinov2-cli failed for ${full_model}" >&2
        exit 1
    fi

    # Parse the single JSON object line with python (avoid jq dep).
    set +e +o pipefail
    bench_stats="$(python3 -c '
import json, sys
data = json.loads(open("'"$bench_json"'").read().strip())
print("{:.1f} {:.1f} {:.0f} {:.0f} {:.0f}".format(data["mean_ms"], data["stddev_ms"], data["min_ms"], data["max_ms"], data["peak_rss_mb"]))
' 2>/dev/null)" || bench_stats=""
    set -e -o pipefail
    if [[ -z "$bench_stats" ]]; then
        echo "::error::could not parse bench output for ${full_model}" >&2
        cat "$bench_json" >&2
        exit 1
    fi
    read -r mean_ms stddev_ms min_ms max_ms peak_rss_mb <<<"$bench_stats"

    printf "| %s | %s | %s | %s | %s | %s | %s | %s |\n" \
        "$v" "$base_gguf" "$gguf_sha256" "$mean_ms" "$stddev_ms" "$min_ms" "$max_ms" "$peak_rss_mb" \
        >> "$OUT_PATH"
done

{
    echo ""
    echo "# Notes:"
    echo "# - \"mean (ms)\" is the forward-pass wall time of the model graph only."
    echo "#   End-to-end wall time (image load + preprocess + classify + PCA) is higher."
    echo "# - \"peak RSS\" is reported by dinov2-cli via getrusage(RUSAGE_SELF)."
    echo "# - Results are generated by the manual bench.yml workflow and should be committed"
    echo "#   with the workflow artifact's model-path and sha256sum provenance."
} >> "$OUT_PATH"

echo "bench.sh: wrote $(wc -l < "$OUT_PATH") rows to $OUT_PATH" >&2
